AdExNetwork/adex-market

helpers/fillInitialValidators.js
index.js
package-lock.json
package.json
routes/validators.js
status-loop/getChannels.js

- Adds initial validators to a mongo collection
- Route for posting validators
- Schema for verification

Validator API

---

package-lock.json
package.json
routes/adSlots.js
routes/adUnits.js

* update adex-models - added slot `website` prop
* adds slot and unit .created date obj (closes #68)

Models update

---

README.md
bin/server.js
cfg.js
helpers/cluster.js

Fixes #77 
The bool that enables clustering is currently in `cfg.js` and defaults to `true`.

Added clustering

---

bin/server.js
db.js
lib/publisherVerification.js
package-lock.json
package.json
routes/adSlots.js
scripts/verify-publisher.js
test/prep-db/seedDb.js

Verification

---

bin/server.js
routes/adSlots.js

Recommended limits

---

README.md
lib/publisherVerification.js

Verify .well-known

---

misc/README.md
misc/cfupdate.sh

Fixes https://github.com/AdExNetwork/adex-market/issues/93

Auxiliary cron script for updating CF FW validated addresses rule

---

bin/server.js
lib/publisherBlacklistedHostnames.js
lib/publisherVerification.js
routes/adSlots.js
scripts/update-verifications.js
test/validatorTestMessages.js

* fixed `verifiedForce` overwrite when ad slot with same website submitted closes #104 
* websites verified by others issue returned with publisher slots
* catch on .well-known check
* lint fix
* return passback units with slot reponse

Slot website verification fix

---

routes/adSlots.js

* return `updated`  value with websites
* updates website in db with site verification on `/verify-website`

Verify website update

---

README.md
lib/publisherVerification.js
package-lock.json
package.json
routes/adSlots.js
scripts/update-verifications.js
scripts/verify-publisher.js

See changes to README for documentation

publisherVerification: integrate webshrinker for better categorization

---

test/index.js

Resolves #112 
Also cleans up the assertion texts of other tests.

#112 Improve test assertion texts

---

routes/adUnits.js
test/integration/integration.js

Necessary for https://github.com/AdExNetwork/adex-supermarket/issues/9
fixes #110

Added type param to /units route

---

routes/adSlots.js

* removes slot integration issue

remove verifiedIntegration issue

---

package-lock.json
package.json
routes/unitsForSlot.js

Turns out, activeFrom may not be defined

Fix spec.created

---

bin/server.js
db.js
lib/publisherVerification.js
package-lock.json
package.json
routes/adSlots.js
routes/adUnits.js
routes/audiences.js
routes/campaigns.js

* Added `slots/targeting-data` route to get current available targeting for active verified publishers
* Added `/audiences` routes GET, POST, PUT, etc.
* Campaign update - `targetingRules` and `audienceInput` (changed from [adex-models](https://github.com/AdExNetwork/adex-models/pull/26))
* TUNED `webshrinkerCategories` filter, fixes #129 
* added `modified` fields on items update (slot, unit, campaign)

New targeting data

---

routes/adSlots.js

* targeting data cleanup and update - closes https://github.com/AdExNetwork/adex-market/issues/134
* Added `minPerImpressionByType` for each hostname

update targeting-data response - added minPerImpressionByType

---

package-lock.json
package.json
routes/adSlots.js

* updates adex-models - slot rules inputs updates
* removed `publisherIds` from slots db query
* `targeting-data` route returns `{ targetingData, minByCategory, countryTiersCoefficients }`
* return `categories` and `suggestedMinCPM` with website verification

Targeting data update

---

package-lock.json
package.json
routes/adSlots.js

* added `totalEarned` to targeting data
* updated adex-models

More targering data

---

test/integration/integration.js
test/run-integration.sh

- Relayer connected to the goerli testnet will always be used while testing
- Commented out tests which add media to ipfs (will fail if not whitelisted) and tests that require the identity to be a verified publisher
- All tests should pass now

Changes to integration tests

---

lib/publisherWebsitesInfo.js
scripts/bigquery.js

related to https://github.com/AdExNetwork/organization/issues/120#issuecomment-666343156
- remove `hostname` www ( as discussed with Galya)
- add `hostname` to campaign
- fix typo in campaign
- if data is missing add N/A

Bigquery requested fixes

---

scripts/bigquery.js

add title to campaigns

---

routes/unitsForSlot.js

Price is also clamped in the output

---

routes/adSlots.js

update default categoties and country cpm cfg

---

scripts/bigquery.js

This adds AdUnits and Audiences so Galya can display them in the Data Studio report.
I only have a few questions on this. 
Do all campaigns right now have audience attached to it? If yes then this should be OK

Bigquery add adunits and targeting

---

routes/campaigns.js

* added `statusOnly` to `GET /campaigns` route - returns only `{ id, creator, status }`

campaugns statusOnly query param and projection

---

routes/adSlots.js

also cosnidering a safety check for webshrinker

adSlots: safety check for hostname

---

package-lock.json
package.json
routes/unitsForSlot.js

- updated models - added CPM update  https://github.com/AdExNetwork/adex-models/pull/30 and https://github.com/AdExNetwork/adex-models/pull/31

Cpm update
